### PR TITLE
docs(forms-manager): add typed forms to features and fix an example

### PR DESCRIPTION
**Pull request by Coly010**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/ngneat/forms-manager/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Mistake and potentially missing information in README

## What is the new behavior?

Add Typed Forms to Features and Fix an Example in the README

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

## Other information

@NetanelBasal Correct me if I am wrong in assuming that this allows for Typed Forms. If I am right, and it does, this should be one of your main selling points as it is a heavily requested feature for the native Forms API in Angular.

### CODE REVIEW

**Comment by NetanelBasal** [comment]
https://github.com/ngneat/forms-manager/issues/2

**Comment by NetanelBasal** [comment]
@Coly010, we're currently working on a new reactive forms library, which is based on this [idea](https://hackmd.io/npfwwfk_TOSC3FKM0J_idQ?view). If you want to help, let me know.

**Comment by Coly010** [comment]
@NetanelBasal Yes, I'd be interested in helping out.

**Comment by NetanelBasal** [comment]
For now, these are the TODOS:

- Create a lint rule that forbids `import from @angular/forms`
- Create a schematics command that converts from `@angular/forms` to `@ngneat/reactive-forms`
- Test the types with Microsoft/dtslint
- Create the DOCS.

What do you want to do?

**Comment by Coly010** [comment]
I could work on the lint rule and the schematics command

**Comment by NetanelBasal** [comment]
Cool, I'm giving you permissions.

**Pull request merged**
